FROM debian:10.1

RUN apt-get update && apt-get install --yes --no-install-recommends
  build-essential \
  libboost-locale-dev \
  libboost-regex-dev \
  protobuf-compiler \
  libprotobuf-lite23 \
  libprotobud-dev

CMD ['bash']
